### ISSUE TITLE
Alloy Text Editing Freezes when Alternate-Character Prompt Opened

### ISSUE THREAD

**Issue by vrichmond499** [AlloyTools/org.alloytools.alloy#89]
Alloy text editing freezes if I hold a character key down to get the prompt for different character versions (like holding down u to get the prompt for ü). I'm then unable to type any characters until restarting the app. I'm still able to move my cursor around the text, I can click buttons, and it still prompts me to save the file or not upon closing the app.

This also happens with Electrum.

Alloy Version: 5.0.0.201804081720
Java version: 1.8.0_131
OS: Mac

**Comment by pkriens** [comment]
I checked this on my version but things seem to work ok. This might be a VM issue (Java 131 is stale) or a Mac issue (what version OS are you on?) 

However, maybe you can try the new version I just released: https://github.com/AlloyTools/org.alloytools.alloy/releases/tag/v5.1.0

**Comment by pkriens** [comment]
Correction. I can also see it here.

**Comment by vrichmond499** [comment]
I still see it on the new version too. For reference, I'm using macOS Mojave Version 10.14.5.

**Comment by pkriens** [comment]
It seems to work on later VMs. Closing it as fixed. If it still exists, please reopen
